name: CI Pipeline

# Execute on pushes to develop or main, as well as all PRs.
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:

  # Run ShellCheck against ShellCheck, pray we don't collapse the universe.
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate

      - name: Run static analysis
        run: composer test
